dbms.memory.heap.max_size=1G
dbms.memory.pagecache.size=512M
dbms.connector.bolt.listen_address=:7687
dbms.connector.http.enabled=false
dbms.security.auth_enabled=true
apoc.trigger.enabled=true
apoc.export.file.enabled=false
